# Este fichero YAML define un recurso ConfigMap en Kubernetes llamado prometheus-config 
# dentro del namespace monitoring-fiona-006.
# El ConfigMap almacena la configuración de Prometheus en la clave prometheus.yml.
# La configuración indica que Prometheus debe hacer scraping cada 15 segundos (scrape_interval: 15s) 
# y define un trabajo llamado prometheus que recolecta métricas del servicio prometheus:9090.
# Este ConfigMap se suele montar en el contenedor de Prometheus para que use esta configuración al iniciar.
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring-fiona-006
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["prometheus-service.monitoring-fiona-006.svc:9090"]
