apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: students-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gonzalodeniz/demo-tfm
        revision: HEAD
        files:
          - path: "gitops-applicationset-apps/alumnos.yaml"
  
  template:
    metadata:
      # CORREGIDO: Acceso directo a la variable sin prefijo 'students.'
      name: '{{nombre}}-apps' 
    spec:
      project: default
      source:
        repoURL: https://github.com/gonzalodeniz/demo-tfm
        targetRevision: HEAD
        path: gitops-applicationset-apps/base
        
        helm:
          parameters:
            # CORREGIDO: Variables directas
            - name: nombre
              value: '{{nombre}}'
            - name: id
              value: '{{id}}'
          # Pasamos la lista de apps tal cual
          values: |
            apps: {{ apps | toJson }}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{nombre}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true