apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: students-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gonzalodeniz/demo-tfm
        revision: HEAD
        files:
          - path: "gitops-applicationset-apps/alumnos.yaml"
  
  template:
    metadata:
      name: '{{nombre}}-apps' 
    spec:
      project: default
      source:
        repoURL: https://github.com/gonzalodeniz/demo-tfm
        targetRevision: HEAD
        path: gitops-applicationset-apps/base
        
        helm:
          parameters:
            - name: nombre
              value: '{{nombre}}'
            - name: id
              value: '{{id}}'
          
          # SOLUCIÓN ROBUSTA: Generamos el YAML línea a línea manualmente.
          # Esto evita errores de parseo de JSON o cadenas.
          values: |
            apps:
            {{- range $app := .apps }}
              - {{ $app }}
            {{- end }}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{nombre}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true