apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: students-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gonzalodeniz/demo-tfm
        revision: HEAD
        files:
          - path: "gitops-applicationset-apps/alumnos.yaml"
  
  template:
    metadata:
      # CORREGIDO: Sin el punto inicial. Debe ser {{nombre}}
      name: '{{nombre}}-apps' 
    spec:
      project: default
      source:
        repoURL: https://github.com/gonzalodeniz/demo-tfm
        targetRevision: HEAD
        path: gitops-applicationset-apps/base
        
        helm:
          parameters:
            - name: nombre
              value: '{{nombre}}'
            - name: id
              value: '{{id}}'
          
          # Usamos 'values' (string) con toJson. 
          # Es el método más robusto para listas en esta versión de ArgoCD.
          values: |
            apps: {{ apps | toJson }}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{nombre}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true