# Recurso Service en Kubernetes para exponer Prometheus dentro del namespace monitoring-marco-013.
#
# El servicio es de tipo ClusterIP y selecciona los pods con la etiqueta app: prometheus.
# Expone el puerto 9090 para acceder a la interfaz web de Prometheus.

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring-marco-013
spec:
  type: NodePort
  selector: {app: prometheus}
  ports:
    - name: tcp
      port: 9090
      targetPort: 9090
      nodePort: 31013 
