# Aplicación ArgoCD llamada alumnos-monitoring.
#
# La aplicación apunta al repositorio demo-tfm en la rama main,
# específicamente a la carpeta gitops-application-monitoring.
# La aplicación se desplegará en el namespace default del clúster Kubernetes.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alumnos-monitoring
  namespace: argocd   
spec:
  project: default
  source:
    repoURL: 'https://github.com/gonzalodeniz/demo-tfm.git'   
    targetRevision: main                                      
    path: gitops-archived/gitops-application/alumnos
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'                 
    namespace: default                                        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
