# Grafana Persistent Volume Claim
# Este PVC se utiliza para almacenar los datos de Grafana de forma persistente.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring-gustavo-033
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 40Mi
