apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
nameSuffix: -monitoring
labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring-stack
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
