apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: student-labs-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: http://a918d57187f9347289c750a4d75c510e-320216334.us-east-1.elb.amazonaws.com/admin/demo-tfm.git
        revision: HEAD
        files:
          - path: aws/gitops-labs-eks/alumnos.yaml

  template:
    metadata:
      name: '{{.nombre}}-apps'
      labels:
        student-id: '{{.id}}'
    spec:
      project: default
      source:
        repoURL: http://a918d57187f9347289c750a4d75c510e-320216334.us-east-1.elb.amazonaws.com/admin/demo-tfm.git
        targetRevision: HEAD
        path: aws/gitops-labs-eks/base
        helm:
          releaseName: '{{.nombre}}'
          parameters:
            - name: nombre
              value: '{{.nombre}}'
            - name: id
              value: '{{.id}}'
          values: |
            {{- $apps := default (list) (get . "apps") }}
            apps:
            {{- range $apps }}
              - {{ . }}
            {{- else }}
              []
            {{- end }}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.nombre}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
