apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alumnos-applicationset
spec:
  generators:
    - git:
        repoURL: 'https://github.com/gonzalodeniz/demo-tfm.git'
        revision: main
        files:
          - path: gitops-applicationset-apps/alumnos.yaml
  template:
    metadata:
      name: 'monitoring-{{nombre}}-{{id}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/gonzalodeniz/demo-tfm.git'
        targetRevision: main
        path: gitops-applicationset-apps/helm-chart
        helm:
          parameters:
            - name: alumno
              value: '{{nombre}}'
            - name: id
              value: '{{id}}'
            - name: namespace
              value: 'monitoring-{{nombre}}-{{id}}'
            - name: grafana.enabled
              value: '{{ grafana | toString | lower }}'
            - name: prometheus.enabled
              value: '{{ prometheus | toString | lower }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'monitoring-{{nombre}}-{{id}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
