apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alumnos-applicationset
spec:
  generators:
    - git:
        repoURL: 'https://github.com/gonzalodeniz/demo-tfm.git'
        revision: main
        files:
          - path: gitops-applicationset-apps/alumnos.yaml
  template:
    metadata:
      name: '{{ printf "monitoring-%s-%v" (regexReplaceAll "[^a-z0-9-]" (lower nombre) "-") id }}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/gonzalodeniz/demo-tfm.git'
        targetRevision: main
        path: gitops-applicationset-apps/helm-chart
        helm:
          values: |
            alumno: "{{nombre}}"
            prometheus: {{prometheus}}
            grafana: {{grafana}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ printf "alumno-%s-%v" (regexReplaceAll "[^a-z0-9-]" (lower nombre) "-") id }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
