# Recurso Secret en Kubernetes para almacenar las credenciales de administrador de Grafana.

apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring-vega-022
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
