apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus/prometheus-configmap.yaml
  - prometheus/prometheus-pvc.yaml
  - prometheus/prometheus-deployment.yaml
  - prometheus/prometheus-service.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
