apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/component: web
    includeSelectors: true
    includeTemplates: true
