{{- $alumno := default "default" .Values.alumno -}}
{{- $sanitizedAlumno := regexReplaceAll "[^a-z0-9-]" (lower $alumno) "-" -}}

{{- if .Values.prometheus }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-{{ $sanitizedAlumno }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: alumno-{{ $sanitizedAlumno }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: prometheus
        app.kubernetes.io/part-of: alumno-{{ $sanitizedAlumno }}
    spec:
      containers:
        - name: prometheus
          image: {{ required "prometheusImage is required" .Values.prometheusImage }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: web
{{- end }}

{{- if and .Values.prometheus .Values.grafana }}
---
{{- end }}

{{- if .Values.grafana }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-{{ $sanitizedAlumno }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: alumno-{{ $sanitizedAlumno }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: grafana
        app.kubernetes.io/part-of: alumno-{{ $sanitizedAlumno }}
    spec:
      containers:
        - name: grafana
          image: {{ required "grafanaImage is required" .Values.grafanaImage }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
{{- end }}
